[hyprshell]
description = "clients overview for hyprland"
version = "0.1"
author = "DreamMaoMao"

[hyprshell.build]
output = "build/libhyprshell.so"
steps = [
  "rm -rf build",
  "cmake -DCMAKE_BUILD_TYPE=Debug -B build",
  "cmake --build build"
]
